@IndigoLabs.Api_HostAddress = https://localhost:7093

### Cache status
GET {{IndigoLabs.Api_HostAddress}}/api/measurements/cache
Authorization: Basic aW5kaWdvOmxhYnM=
Accept: application/json

### All cities
GET {{IndigoLabs.Api_HostAddress}}/api/cities
Authorization: Basic aW5kaWdvOmxhYnM=
Accept: application/json

### Single city
GET {{IndigoLabs.Api_HostAddress}}/api/cities/Paris
Authorization: Basic aW5kaWdvOmxhYnM=
Accept: application/json

### Average temperature greater than X
GET {{IndigoLabs.Api_HostAddress}}/api/cities/average-temperature/greater-than/25
Authorization: Basic aW5kaWdvOmxhYnM=
Accept: application/json

### Average temperature less than X
GET {{IndigoLabs.Api_HostAddress}}/api/cities/average-temperature/less-than/0
Authorization: Basic aW5kaWdvOmxhYnM=
Accept: application/json

### Manual cache recalculation
POST {{IndigoLabs.Api_HostAddress}}/api/measurements/recalculate
Authorization: Basic aW5kaWdvOmxhYnM=
Accept: application/json
